// <auto-generated />
namespace CECHarmonization.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ned : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ned));
        
        string IMigrationMetadata.Id
        {
            get { return "201506101950323_ned"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
