// <auto-generated />
namespace CECHarmonization.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class map12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(map12));
        
        string IMigrationMetadata.Id
        {
            get { return "201505261506271_map12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
