//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class cohort_script_vw
    {
        public string entity_type { get; set; }
        public string bundle { get; set; }
        public sbyte deleted { get; set; }
        public long entity_id { get; set; }
        public Nullable<long> revision_id { get; set; }
        public string language { get; set; }
        public long delta { get; set; }
        public Nullable<long> field_study_study_variable_att_nid { get; set; }
        public string title { get; set; }
        public string cohort_title { get; set; }
        public string field_sva_status_value { get; set; }
        public string field_sva_comment_value { get; set; }
        public string field_sva_script_value { get; set; }
    }
}
