//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicaData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dataset_vw> dataset_vw { get; set; }
        public DbSet<taxonomy_vw> taxonomy_vw { get; set; }
        public DbSet<taxvarmap_vw> taxvarmap_vw { get; set; }
        public DbSet<variable_vw> variable_vw { get; set; }
        public DbSet<short_variable_vw> short_variable_vw { get; set; }
        public DbSet<field_data_field_sva_comment> field_data_field_sva_comment { get; set; }
        public DbSet<field_data_field_sva_script> field_data_field_sva_script { get; set; }
        public DbSet<field_data_field_sva_status> field_data_field_sva_status { get; set; }
        public DbSet<study_vw> study_vw { get; set; }
        public DbSet<field_data_field_sva_variable> field_data_field_sva_variable { get; set; }
        public DbSet<mica_vw> mica_vw { get; set; }
        public DbSet<cohort_script_vw> cohort_script_vw { get; set; }
    
        public virtual int clear_cache()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("clear_cache");
        }
    }
}
