//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class mica_vw
    {
        public long entity_id { get; set; }
        public string field_sva_comment_value { get; set; }
        public string field_sva_script_value { get; set; }
        public string field_sva_status_value { get; set; }
    }
}
