//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class short_variable_vw
    {
        public long nid { get; set; }
        public Nullable<long> vid { get; set; }
        public string title { get; set; }
        public int status { get; set; }
        public Nullable<long> dataset_id { get; set; }
        public string dataset_name { get; set; }
        public string id { get; set; }
    }
}
