//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class variable_vw
    {
        public long nid { get; set; }
        public Nullable<long> vid { get; set; }
        public string title { get; set; }
        public int status { get; set; }
        public string field_label_value { get; set; }
        public Nullable<long> dataset_id { get; set; }
        public string dataset_name { get; set; }
        public Nullable<long> entity_id { get; set; }
        public string entity_type { get; set; }
        public Nullable<long> delta { get; set; }
        public string field_variable_categories_name { get; set; }
        public string field_variable_categories_label { get; set; }
        public Nullable<int> field_variable_categories_missing { get; set; }
        public string field_unit_value { get; set; }
        public string field_value_type_value { get; set; }
        public string body_value { get; set; }
        public Nullable<long> study_id { get; set; }
        public string study_name { get; set; }
    }
}
